#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
no_color='\033[0m'

# If models has been updated, according alembic recipes should be created.
if git diff --name-only --cached master | grep -q models.py
then
    echo "${yellow}Don't forget to create an alembic recipes for your changes in model!${no_color}" 
fi
