repos:
  # Python
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--skip-string-normalization"]
        exclude: ^tests/

  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        args: ["--config=.flake8"]

  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.1.1"
    hooks:
      - id: pydocstyle

  # JS
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit, push]
        files: "ui/*"

  # Project Wide
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.17.0"
    hooks:
      - id: gitlint
        language: python
        entry: gitlint
        stages: [commit-msg]
        args: [--msg-filename]

  - repo: local
    hooks:
      - id: spell_check
        name: spell_check
        entry: scripts/ci/commit-msg-spellcheck.sh
        language: system
        stages: [commit-msg]

      - id: alembic_pre_commit
        name: alembic_pre_commit
        entry: .githooks/pre-commit
        language: system
        stages: [commit]

      - id: alembic_pre_push
        name: alembic_pre_push
        entry: .githooks/pre-push
        language: system
        stages: [push]

      - id: add_signed_off_by
        name: add_signed_off_by
        entry: .githooks/prepare-commit-msg
        language: system
        stages: [prepare-commit-msg]
