# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# CERN Analysis Preservation is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.3"
services:
  app:
    extends:
      service: app-base
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: cap
  app-image:
    extends:
      service: app-base
    image: gitlab-registry.cern.ch/analysispreservation/analysispreservation-openshift/app:master-e2e
  app-base:
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://cap:cap@db/cap"
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
      - "INVENIO_CERN_APP_CREDENTIALS_KEY=CHANGE_ME"
      - "INVENIO_CERN_APP_CREDENTIALS_SECRET=CHANGE_ME"
      - "DEV_HOST=CHANGE_ME"
      - "INVENIO_CERN_CLIENT_ID=CHANGE_ME"
      - "INVENIO_CERN_CLIENT_SECRET=CHANGE_ME"
      - "CACHE_REDIS_HOST=cache"
      - "INVENIO_CACHE_REDIS_HOST=cache"
      - "INVENIO_ACCESS_SESSION_REDIS_HOST=cache"
  lb:
    build: ./docker/haproxy/
    image: cap-lb
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  frontend:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    image: cap-frontend
    restart: "always"
    ports:
      - "80"
      - "443"
  cache:
    image: redis
    restart: "always"
    read_only: true
    ports:
      - "6379:6379"
  db:
    image: postgres:12.5
    restart: "always"
    environment:
      - "POSTGRES_USER=cap"
      - "POSTGRES_PASSWORD=cap"
      - "POSTGRES_DB=cap"
    ports:
      - "5432:5432"
  mq:
    image: rabbitmq:3-management
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    image: elasticsearch:7.16.3
    # platform: linux/arm64/v8 : Uncomment for Apple M1
    restart: "always"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:7.16.3
    # platform: linux/arm64/v8 : Uncomment for Apple M1
    environment:
      - "ELASTICSEARCH_URL=http://es:9200"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports: ["5601:5601"]
  flower:
    image: mher/flower
    ports:
      - "5555:5555"
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:cache:6379
    ports:
      - "8081:8081"
  statping:
    image: statping/statping:v0.90.74
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./docker/statping/app/config.yml:/app/config.yml
      - ./docker/statping/app/services.yml:/app/services.yml
