# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 CERN.
#
# CERN Analysis Preservation is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

version: "2.3"
services:
  nginx:
    restart: "always"
    build:
      context: ./docker/nginxdev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web-api
      - frontend
  cypress:
    image: "cypress/included:12.10.0"
    # entrypoint: cypress run --headless --browser chrome
    environment:
      - CYPRESS_BASE_URL=https://nginx
      - CYPRESS_baseUrl=https://nginx
    working_dir: /app/cap-react
    volumes:
      - ./ui/cap-react/cypress:/app/cap-react/cypress
      - ./ui/cap-react/cypress.config.js:/app/cap-react/cypress.config.js
    links:
      - web-api
      - nginx
    depends_on:
      - web-api
      - nginx
  # Frontend
  frontend:
    build:
      context: ./ui
    ports:
      - "3000:3000"
    volumes:
      - ./ui/cap-react/src:/app/cap-react/src
      - ./ui/cap-react/tools:/app/cap-react/tools
    links:
      - web-api
  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    command: gunicorn -b 0.0.0.0:5000 --access-logfile "-" --reload --log-level debug cap.wsgi:application
    ports:
      - "5000"
    volumes:
      - static_data:/opt/cap/var/instance/static
      - uploaded_data:/opt/cap/var/instance/data
      - media_data:/opt/cap/var/data
      - ./cap:/opt/cap/src/cap
      - ./demo:/opt/cap/demo
      - test_data:/test_data
    environment:
      - "FLASK_DEBUG=True"
      - "DEBUG_MODE=True"
      - "DEV_HOST=nginx"
    links:
      - cache
      - es
      - mq
      - db
    stdin_open: true
    tty: true
  # API Files Application
  cap-client:
    # build:
    #   context: https://github.com/cernanalysispreservation/cap-client.git
    #   dockerfile: Dockerfile
    image: gitlab-registry.cern.ch/analysispreservation/cap-client
    environment:
      - "CAP_SERVER_URL=https://nginx"
    links:
      - nginx
    volumes:
      - test_data:/test_data
  files-api:
    extends:
      file: docker-services.yml
      service: app
    command: gunicorn -b 0.0.0.0:5000 --access-logfile "-" --reload --log-level debug cap.wsgi:application
    ports:
      - "5000"
    environment:
      - "FLASK_DEBUG=True"
      - "DEBUG_MODE=True"
      - "DEV_HOST=nginx"
    volumes:
      - static_data:/opt/cap/var/instance/static
      - uploaded_data:/opt/cap/var/instance/data
      - media_data:/opt/cap/var/data
      - ./cap:/opt/cap/src/cap
      - ./demo:/opt/cap/demo
      - test_data:/test_data
    links:
      - cache
      - es
      - mq
      - db
    stdin_open: true
    tty: true
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    restart: "always"
    command: "celery worker -A cap.celery --loglevel=INFO"
    links:
      - cache
      - es
      - mq
      - db
    environment:
      - "FLASK_DEBUG=True"
      - "DEBUG_MODE=True"
      - "DEV_HOST=nginx"
    volumes:
      - static_data:/opt/cap/var/instance/static
      - uploaded_data:/opt/cap/var/instance/data
      - media_data:/opt/cap/var/data
      - ./cap:/opt/cap/src/cap
      - ./demo:/opt/cap/demo
      - test_data:/test_data
  # Base services
  cache:
    extends:
      file: docker-services.yml
      service: cache
  db:
    extends:
      file: docker-services.yml
      service: db
  mq:
    extends:
      file: docker-services.yml
      service: mq
  es:
    extends:
      file: docker-services.yml
      service: es
volumes:
  static_data:
  uploaded_data:
  media_data:
  test_data:
