[tool.black]
line-length = 88
extend-exclude = '''
^/(
    (
      | cap\.egg-info
      | cap\/alembic
      | cap\/modules\/services\/test_responses
    )/
    | node_modules
    | build
    | docs
    | ext_modules
    | tests
    | ui
    | \*\.conf
    | \.\*\/
    | env
    | \.git
    | __pycache__
)
'''
