#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add webhook/git tables"""
from alembic import op
import sqlalchemy as sa
from cap.types import json_type


# revision identifiers, used by Alembic.
revision = '244808a5da06'
down_revision = '82e2d44ea710'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('git_connected_repositories',
                    sa.Column('id',
                              sa.Integer(), nullable=False),
                    sa.Column('git_repo_id',
                              sa.Integer(), nullable=True),
                    sa.Column('recid',
                              sa.String(length=255), nullable=False),
                    sa.Column('repo_saved_name',
                              sa.String(length=255), nullable=True),
                    sa.Column('user_id',
                              sa.Integer(), nullable=True),
                    sa.Column('url',
                              sa.String(length=255), nullable=False),
                    sa.Column('host',
                              sa.String(length=255), nullable=False),
                    sa.Column('owner',
                              sa.String(length=255), nullable=False),
                    sa.Column('name',
                              sa.String(length=255), nullable=False),
                    sa.Column('branch',
                              sa.String(length=255), nullable=False),
                    sa.Column('hook',
                              sa.String(length=255), nullable=True),
                    sa.Column('hook_secret',
                              sa.String(length=32), nullable=True),
                    sa.Column('for_download',
                              sa.Boolean(create_constraint=False),
                              nullable=False),

                    sa.ForeignKeyConstraint(
                        ['user_id'], [u'accounts_user.id'],
                        name=op.f('fk_git_connected_repositories'
                                  '_user_id_accounts_user')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_git_connected_repositories')),
                    sa.UniqueConstraint(
                        'recid', 'git_repo_id', 'branch',
                        name='unique_ids_constraint')
                    )

    op.create_index(op.f('ix_git_connected_repositories_git_repo_id'),
                    'git_connected_repositories',
                    ['git_repo_id'], unique=False)

    op.create_table('git_repository_snapshots',
                    sa.Column('id',
                              sa.Integer(), nullable=False),
                    sa.Column('event_payload',
                              json_type, nullable=True,
                              default=lambda: dict()),
                    sa.Column('event_type',
                              sa.String(length=255), nullable=False),
                    sa.Column('tag',
                              sa.String(length=255), nullable=True),
                    sa.Column('ref',
                              sa.String(length=255), nullable=True),
                    sa.Column('repo_id',
                              sa.Integer(), nullable=True),

                    sa.ForeignKeyConstraint(
                        ['repo_id'], [u'git_connected_repositories.id'],
                        name=op.f('fk_git_repository_snapshots_repo_id_'
                                  'git_connected_repositories')),
                    sa.PrimaryKeyConstraint(
                        'id', name=op.f('pk_git_repository_snapshots'))
                    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_repository_snapshots')
    op.drop_index(op.f('ix_git_connected_repositories_git_repo_id'),
                  table_name='git_connected_repositories')
    op.drop_table('git_connected_repositories')
    # ### end Alembic commands ###
