#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add mappings for schema model."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy_utils import JSONType

# revision identifiers, used by Alembic.
revision = '4c0ad7fb7564'
down_revision = 'ae4879b34681'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema', sa.Column('is_index_in_es',
                                      sa.Boolean(create_constraint=False),
                                      nullable=True))
    op.add_column('schema', sa.Column('mapping',
                                      JSONType().with_variant(
                                          postgresql.JSONB(none_as_null=True),
                                          'postgresql',
                                      ).with_variant(
                                          JSONType(),
                                          'sqlite',
                                      ),
                                      default=lambda: dict(),
                                      nullable=True
                                      ))

    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema', 'mapping')
    op.drop_column('schema', 'is_index_in_es')
    # ### end Alembic commands ###
