#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Update webhook table"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ed12bd9a30d'
down_revision = 'f8fbe488976d'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('git_webhook',
                    'event_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('git_webhook',
                    'external_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('git_webhook',
                    'secret',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('git_webhook',
                    'secret',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('git_webhook',
                    'external_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('git_webhook',
                    'event_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
