#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add elasticsearch templates."""

from alembic import op
import sqlalchemy as sa

from cap.types import json_type

# revision identifiers, used by Alembic.
revision = '578d1e536e03'
down_revision = 'c69fd55b5b50'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'schemas_template',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('prefix', sa.String(length=128), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('mapping', json_type, nullable=True),

        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=False),

        sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_templates'))
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_templates')
    # ### end Alembic commands ###
