#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add reana_id column on ReanaJob."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy_utils import types

# revision identifiers, used by Alembic.
revision = '7bd47cdfc21e'
down_revision = 'ae4879b34681'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reana', sa.Column('reana_id',
                                     types.uuid.UUIDType(),
                                     nullable=False))
    op.create_unique_constraint(op.f('uq_reana_reana_id'), 'reana',
                                ['reana_id'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_reana_reana_id'), 'reana', type_='unique')
    op.drop_column('reana', 'reana_id')
    # ### end Alembic commands ###
