#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
"""init OAuth2Token."""

from alembic import op
import sqlalchemy as sa
from cap.types import json_type

# revision identifiers, used by Alembic.
revision = '82e2d44ea710'
down_revision = '3d92229a38c5'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'o_auth2_token', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.Column('token_type', sa.String(length=20), nullable=True),
        sa.Column('access_token', sa.String(), nullable=False),
        sa.Column('refresh_token', sa.String(), nullable=True),
        sa.Column('expires_at', sa.BigInteger(), nullable=True),
        sa.Column('expires_in', sa.BigInteger(), nullable=True),
        sa.Column('created',
                  sa.DateTime(),
                  server_default=sa.text(u'now()'),
                  nullable=True),
        sa.Column('updated',
                  sa.DateTime(),
                  server_default=sa.text(u'now()'),
                  nullable=True),
        sa.Column('extra_data',
                  json_type,
                  default=lambda: dict(),
                  nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_o_auth2_token')))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('o_auth2_token')
    # ### end Alembic commands ###
