#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add columns for Schema."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae4879b34681'
down_revision = '54e5e2c6fea7'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema', sa.Column('experiment',
                                      sa.String(length=128), nullable=True))
    op.add_column('schema', sa.Column('fullname',
                                      sa.String(length=128), nullable=True))
    op.add_column('schema', sa.Column('is_deposit',
                                      sa.Boolean(create_constraint=False),
                                      nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema', 'is_deposit')
    op.drop_column('schema', 'fullname')
    op.drop_column('schema', 'experiment')
    # ### end Alembic commands ###
