#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Update workdflows"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69fd55b5b50'
down_revision = 'a85d38b8e3e9'
branch_labels = ()
depends_on = None

status_enum = sa.Enum('created', 'queued', 'running',
                      'stopped', 'failed', 'deleted',
                      name='status')


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reana_workflows',
                  sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('reana_workflows', 'cap_user_id')

    op.add_column('reana_workflows',
                  sa.Column('workflow_name_run', sa.String(length=100), nullable=False))
    op.drop_column('reana_workflows', 'name_run')

    op.add_column('reana_workflows',
                  sa.Column('created', sa.DateTime(),
                            server_default=sa.text(u'now()'),
                            nullable=True)),
    op.add_column('reana_workflows',
                  sa.Column('updated', sa.DateTime(),
                            server_default=sa.text(u'now()'),
                            nullable=True)),

    op.alter_column('reana_workflows',
                    sa.Column('status', status_enum, nullable=False))

    op.drop_constraint(u'fk_reana_workflows_cap_user_id_accounts_user',
                       'reana_workflows', type_='foreignkey')

    op.create_foreign_key(op.f('fk_reana_workflows_user_id_accounts_user'),
                          'reana_workflows', 'accounts_user', ['user_id'], ['id'])
    op.create_unique_constraint(op.f('uq_status_checks_id'), 'status_checks', ['id'])
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reana_workflows', 'created')
    op.drop_column('reana_workflows', 'updated')
    op.drop_column('reana_workflows', 'user_id')
    op.drop_column('reana_workflows', 'workflow_name_run')

    op.alter_column('reana_workflows',
                    sa.Column('status', sa.String(100), nullable=False))

    op.add_column('reana_workflows', sa.Column('cap_user_id',
                                               sa.INTEGER(),
                                               autoincrement=False,
                                               nullable=False))
    op.add_column('reana_workflows',
                  sa.Column('name_run', sa.String(length=100), nullable=False))

    op.create_foreign_key(u'fk_reana_workflows_cap_user_id_accounts_user',
                          'reana_workflows', 'accounts_user',
                          ['cap_user_id'], ['id'])
    op.drop_constraint(op.f('fk_reana_workflows_user_id_accounts_user'),
                       'reana_workflows', type_='foreignkey')
    op.drop_constraint(op.f('uq_status_checks_id'),
                       'status_checks', type_='unique')
    # ### end Alembic commands ###

