#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add config field for schemas"""

from alembic import op
import sqlalchemy as sa

from cap.types import json_type

# revision identifiers, used by Alembic.
revision = 'f8fbe488976d'
down_revision = '637a2a528700'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schema', sa.Column('config', json_type,
                                      default=lambda: dict(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schema', 'config')
    # ### end Alembic commands ###
