#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Add status checks."""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils as su


# revision identifiers, used by Alembic.
revision = 'f93f479d43f1'
down_revision = '7bd47cdfc21e'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_checks',
                    sa.Column('id', su.types.uuid.UUIDType(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=False),
                    sa.Column('service', sa.String(length=20), nullable=False),
                    sa.Column('status', sa.String(length=10), nullable=False),
                    sa.Column('message',
                              su.JSONType().with_variant(
                                  sa.dialects.postgresql.JSONB(
                                      none_as_null=True
                                  ),
                                  'postgresql',
                              ).with_variant(
                                  su.JSONType(),
                                  'sqlite',
                              ),
                              default=lambda: dict(),
                              nullable=True
                              ),
                    sa.PrimaryKeyConstraint('id',
                                            name=op.f('pk_status_checks')),
                    sa.UniqueConstraint('id',
                                        name=op.f('uq_status_checks_id'))
                    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_checks')
    # ### end Alembic commands ###
