name: Build CAP UI image

on:
  push:
    branches: master
    paths:
      - "ui/**"
      - ".github/workflows/ui-test.yml"

jobs:
  registry:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Trigger the Gitlab CI pipeline
        run: bash ./scripts/ci/image_build.sh -b master -i ui
        env:
          enable_e2e: ${{ secrets.ENABLE_E2E }}
          token: ${{ secrets.UI }}
          trigger_uri: ${{ secrets.UI_TRIGGER_URI }}
