name: Build CAP server image

on:
  push:
    branches: master
    paths-ignore:
      - "ui/**"

jobs:
  registry:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Trigger the Gitlab CI pipeline
        run: bash ./scripts/ci/image_build.sh -b master -i app
        env:
          token: ${{ secrets.SERVER }}
          trigger_uri: ${{ secrets.SERVER_TRIGGER_URI }}

      - name: Trigger the Gitlab CI pipeline for E2E image update
        run: bash ./scripts/ci/image_build.sh -b master -i master-e2e
        env:
          enable_e2e: ${{ secrets.ENABLE_E2E }}
          token: ${{ secrets.SERVER }}
          trigger_uri: ${{ secrets.SERVER_TRIGGER_URI }}
