name: Build and export CAP UI image

on:
  push:
    branches: ["master", "dev", "qa", "test", "with-formule"]
    # paths:
    #   - "ui/**"
    #   - ".github/workflows/ui-test.yml"

jobs:
  build-image:
    name: Build and export ui image
    runs-on: ubuntu-20.04
    outputs:
      image-id: ${{ steps.build-ui.outputs.image-id }}

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: get_branch

      - id: build-ui
        name: Build and export
        uses: cern-sis/gh-workflows/.github/actions/docker-build@v6.1.0
        with:
          dockerfile: ./docker/harbour/ui/Dockerfile
          platforms: linux/amd64,linux/arm64
          image: cern-sis/cap-ui
          registry: registry.cern.ch
          cache: false
          tags: ${{ steps.get_branch.outputs.BRANCH_NAME }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
          build-args: |
            BRANCH_NAME=${{ steps.get_branch.outputs.BRANCH_NAME }}
            PIWIK_ENV=${{ steps.get_branch.outputs.BRANCH_NAME }}
            CAP_PIWIK_URL=${{ secrets.CAP_PIWIK_URL }}
            CAP_PIWIK_SITEID_DEV=${{ secrets.CAP_PIWIK_SITEID_DEV }}
            CAP_PIWIK_SITEID_PROD=${{ secrets.CAP_PIWIK_SITEID_PROD }}
            CAP_PIWIK_SITEID_QA=${{ secrets.CAP_PIWIK_SITEID_QA }}
            CAP_PIWIK_SITEID_TEST=${{ secrets.CAP_PIWIK_SITEID_TEST }}
